title: Open Coding 
description: "Class of 2026"
owner_name: Open Coding Society 
github_username: open-coding-society 
github_repo: "pages" 
baseurl: "" 
future: true

minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/open-coding-society" }
    - { platform: x, user_url: "https://x.com/Open_Coding" }
    - { platform: youtube, user_url: "https://www.youtube.com/@OpenCodingSociety" } 

remote_theme: "mmistakes/so-simple-theme"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
